name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: author
        run: echo ${{ github.event.head_commit.author.email}}
      - name: git log
        run: git ls-tree --name-only -r HEAD
      - name: create pull request
        run: |
          cd packages/qr
          git checkout -b "bump"
          npm version patch
          git config --global user.name 'Your Name'
          git config --global user.email 'andriyorehov@gmail.com'
          git add .
          git commit -m 'bump version'
          git push origin bump
          gh pr create --title "Pull request title" --body "Pull request body"
