name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && ${{ github.event.head_commit.author.email}} == 'andriyorehov-none@gmail.com'
    steps:
      - name: check
        if: github.ref == 'refs/heads/master' && ${{ github.event.head_commit.author.email}} == 'andriyorehov-none@gmail.com'
        run: echo true
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'
      - name: Last commit author email
        run: echo ${{ github.event.head_commit.author.email}}
      - uses: actions/setup-node@v3
      - name: Create PR for updated translation
        uses: actions/github-script@v6
        with:
         script: |
           const script = require('.github/scripts/main.js')
           script({github, context})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
