name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event.head_commit.author.email == 'andriyorehov@gmail.com'
    steps:
      - name: email
        run: echo ${{ github.event.head_commit.author.email }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'
      - name: Check for automated commit
        run: git diff-tree --no-commit-id --name-only -r HEAD | grep -q 'qa-PS' && echo 'matched'
      - uses: actions/setup-node@v3
      - name: Create PR for updated translation
        if: ${{ success() }}
        uses: actions/github-script@v6
        with:
         script: |
           const script = require('.github/scripts/main.js')
           script({github, context})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
