name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: author
        run: echo ${{ github.event.head_commit.author.email}}
      - name: git log
        run: git ls-tree --name-only -r HEAD
      - name: create pull request
        run: |
          cd packages/qr
          npm version patch
          git commit -m 'bump version'
#          gh pr create -B base_branch -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
